{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "WoP8dMd9FcEU"
   },
   "source": [
    "# Data Cleaning"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "id": "t4TjJfQ1IRms",
    "outputId": "0419d698-768f-4296-92d6-7bb6b5b7220a"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: streamlit in d:\\aanconda new\\lib\\site-packages (1.51.0)\n",
      "Requirement already satisfied: altair!=5.4.0,!=5.4.1,<6,>=4.0 in d:\\aanconda new\\lib\\site-packages (from streamlit) (5.5.0)\n",
      "Requirement already satisfied: blinker<2,>=1.5.0 in d:\\aanconda new\\lib\\site-packages (from streamlit) (1.9.0)\n",
      "Requirement already satisfied: cachetools<7,>=4.0 in d:\\aanconda new\\lib\\site-packages (from streamlit) (5.5.1)\n",
      "Requirement already satisfied: click<9,>=7.0 in d:\\aanconda new\\lib\\site-packages (from streamlit) (8.2.1)\n",
      "Requirement already satisfied: numpy<3,>=1.23 in d:\\aanconda new\\lib\\site-packages (from streamlit) (2.3.5)\n",
      "Requirement already satisfied: packaging<26,>=20 in d:\\aanconda new\\lib\\site-packages (from streamlit) (25.0)\n",
      "Requirement already satisfied: pandas<3,>=1.4.0 in d:\\aanconda new\\lib\\site-packages (from streamlit) (2.3.3)\n",
      "Requirement already satisfied: pillow<13,>=7.1.0 in d:\\aanconda new\\lib\\site-packages (from streamlit) (12.0.0)\n",
      "Requirement already satisfied: protobuf<7,>=3.20 in d:\\aanconda new\\lib\\site-packages (from streamlit) (5.29.3)\n",
      "Requirement already satisfied: pyarrow<22,>=7.0 in d:\\aanconda new\\lib\\site-packages (from streamlit) (21.0.0)\n",
      "Requirement already satisfied: requests<3,>=2.27 in d:\\aanconda new\\lib\\site-packages (from streamlit) (2.32.5)\n",
      "Requirement already satisfied: tenacity<10,>=8.1.0 in d:\\aanconda new\\lib\\site-packages (from streamlit) (9.1.2)\n",
      "Requirement already satisfied: toml<2,>=0.10.1 in d:\\aanconda new\\lib\\site-packages (from streamlit) (0.10.2)\n",
      "Requirement already satisfied: typing-extensions<5,>=4.4.0 in d:\\aanconda new\\lib\\site-packages (from streamlit) (4.15.0)\n",
      "Requirement already satisfied: watchdog<7,>=2.1.5 in d:\\aanconda new\\lib\\site-packages (from streamlit) (4.0.2)\n",
      "Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in d:\\aanconda new\\lib\\site-packages (from streamlit) (3.1.45)\n",
      "Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in d:\\aanconda new\\lib\\site-packages (from streamlit) (6.5.1)\n",
      "Requirement already satisfied: jinja2 in d:\\aanconda new\\lib\\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.1.6)\n",
      "Requirement already satisfied: jsonschema>=3.0 in d:\\aanconda new\\lib\\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (4.25.0)\n",
      "Requirement already satisfied: narwhals>=1.14.2 in d:\\aanconda new\\lib\\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2.7.0)\n",
      "Requirement already satisfied: colorama in d:\\aanconda new\\lib\\site-packages (from click<9,>=7.0->streamlit) (0.4.6)\n",
      "Requirement already satisfied: gitdb<5,>=4.0.1 in d:\\aanconda new\\lib\\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)\n",
      "Requirement already satisfied: smmap<6,>=3.0.1 in d:\\aanconda new\\lib\\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in d:\\aanconda new\\lib\\site-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in d:\\aanconda new\\lib\\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)\n",
      "Requirement already satisfied: tzdata>=2022.7 in d:\\aanconda new\\lib\\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in d:\\aanconda new\\lib\\site-packages (from requests<3,>=2.27->streamlit) (3.4.4)\n",
      "Requirement already satisfied: idna<4,>=2.5 in d:\\aanconda new\\lib\\site-packages (from requests<3,>=2.27->streamlit) (3.11)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in d:\\aanconda new\\lib\\site-packages (from requests<3,>=2.27->streamlit) (2.5.0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in d:\\aanconda new\\lib\\site-packages (from requests<3,>=2.27->streamlit) (2026.4.22)\n",
      "Requirement already satisfied: attrs>=22.2.0 in d:\\aanconda new\\lib\\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (25.4.0)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in d:\\aanconda new\\lib\\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2025.9.1)\n",
      "Requirement already satisfied: referencing>=0.28.4 in d:\\aanconda new\\lib\\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.37.0)\n",
      "Requirement already satisfied: rpds-py>=0.7.1 in d:\\aanconda new\\lib\\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.28.0)\n",
      "Requirement already satisfied: six>=1.5 in d:\\aanconda new\\lib\\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in d:\\aanconda new\\lib\\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.0.2)\n"
     ]
    }
   ],
   "source": [
    "!pip install streamlit"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import plotly.express as px"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "id": "pqbasAWwSdcb",
    "outputId": "8257db5f-cacc-41e5-f76a-a3d5e67ddf73"
   },
   "outputs": [],
   "source": [
    "df = pd.read_csv('Walmart_Sales.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 399
    },
    "id": "9b5f4146",
    "outputId": "8707c342-76b8-4ad9-fe4a-04f2954d7c66"
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Store</th>\n",
       "      <th>Date</th>\n",
       "      <th>Weekly_Sales</th>\n",
       "      <th>Holiday_Flag</th>\n",
       "      <th>Temperature</th>\n",
       "      <th>Fuel_Price</th>\n",
       "      <th>CPI</th>\n",
       "      <th>Unemployment</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1</td>\n",
       "      <td>05-02-2010</td>\n",
       "      <td>1643690.90</td>\n",
       "      <td>0</td>\n",
       "      <td>42.31</td>\n",
       "      <td>2.572</td>\n",
       "      <td>211.096358</td>\n",
       "      <td>8.106</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1</td>\n",
       "      <td>12-02-2010</td>\n",
       "      <td>1641957.44</td>\n",
       "      <td>1</td>\n",
       "      <td>38.51</td>\n",
       "      <td>2.548</td>\n",
       "      <td>211.242170</td>\n",
       "      <td>8.106</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>1</td>\n",
       "      <td>19-02-2010</td>\n",
       "      <td>1611968.17</td>\n",
       "      <td>0</td>\n",
       "      <td>39.93</td>\n",
       "      <td>2.514</td>\n",
       "      <td>211.289143</td>\n",
       "      <td>8.106</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>1</td>\n",
       "      <td>26-02-2010</td>\n",
       "      <td>1409727.59</td>\n",
       "      <td>0</td>\n",
       "      <td>46.63</td>\n",
       "      <td>2.561</td>\n",
       "      <td>211.319643</td>\n",
       "      <td>8.106</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>1</td>\n",
       "      <td>05-03-2010</td>\n",
       "      <td>1554806.68</td>\n",
       "      <td>0</td>\n",
       "      <td>46.50</td>\n",
       "      <td>2.625</td>\n",
       "      <td>211.350143</td>\n",
       "      <td>8.106</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   Store        Date  Weekly_Sales  Holiday_Flag  Temperature  Fuel_Price  \\\n",
       "0      1  05-02-2010    1643690.90             0        42.31       2.572   \n",
       "1      1  12-02-2010    1641957.44             1        38.51       2.548   \n",
       "2      1  19-02-2010    1611968.17             0        39.93       2.514   \n",
       "3      1  26-02-2010    1409727.59             0        46.63       2.561   \n",
       "4      1  05-03-2010    1554806.68             0        46.50       2.625   \n",
       "\n",
       "          CPI  Unemployment  \n",
       "0  211.096358         8.106  \n",
       "1  211.242170         8.106  \n",
       "2  211.289143         8.106  \n",
       "3  211.319643         8.106  \n",
       "4  211.350143         8.106  "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "display(df.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "id": "kOoEMTCWJT-5"
   },
   "outputs": [],
   "source": [
    "df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)\n",
    "df = df.sort_values(by='Date')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "id": "fcbLdgRfJfVL"
   },
   "outputs": [],
   "source": [
    "# Winsorize Outliers at 99th percentile\n",
    "cap_value = df[\"Weekly_Sales\"].quantile(0.99)\n",
    "df[\"Weekly_Sales\"] = df[\"Weekly_Sales\"].clip(upper=cap_value)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "id": "wTk8N3yeJoa-"
   },
   "outputs": [],
   "source": [
    "# Standardize Holiday Flag\n",
    "df[\"Holiday_Status\"] = df[\"Holiday_Flag\"].map({1: \"Holiday Week\", 0: \"Regular Week\"})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {
    "id": "y2QH8f_GJxmx"
   },
   "outputs": [],
   "source": [
    "# Logic check for negative values\n",
    "numeric_cols = [\"Weekly_Sales\", \"Fuel_Price\", \"CPI\", \"Unemployment\"]\n",
    "df[numeric_cols] = df[numeric_cols].abs()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 617
    },
    "id": "eEjwl-QTJx9F",
    "outputId": "0469a973-3041-4eca-8a95-2f3cceabb490"
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Store</th>\n",
       "      <th>Date</th>\n",
       "      <th>Weekly_Sales</th>\n",
       "      <th>Holiday_Flag</th>\n",
       "      <th>Temperature</th>\n",
       "      <th>Fuel_Price</th>\n",
       "      <th>CPI</th>\n",
       "      <th>Unemployment</th>\n",
       "      <th>Holiday_Status</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1</td>\n",
       "      <td>2010-02-05</td>\n",
       "      <td>1643690.90</td>\n",
       "      <td>0</td>\n",
       "      <td>42.31</td>\n",
       "      <td>2.572</td>\n",
       "      <td>211.096358</td>\n",
       "      <td>8.106</td>\n",
       "      <td>Regular Week</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1287</th>\n",
       "      <td>10</td>\n",
       "      <td>2010-02-05</td>\n",
       "      <td>2193048.75</td>\n",
       "      <td>0</td>\n",
       "      <td>54.34</td>\n",
       "      <td>2.962</td>\n",
       "      <td>126.442065</td>\n",
       "      <td>9.765</td>\n",
       "      <td>Regular Week</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5148</th>\n",
       "      <td>37</td>\n",
       "      <td>2010-02-05</td>\n",
       "      <td>536006.73</td>\n",
       "      <td>0</td>\n",
       "      <td>45.97</td>\n",
       "      <td>2.572</td>\n",
       "      <td>209.852966</td>\n",
       "      <td>8.554</td>\n",
       "      <td>Regular Week</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2288</th>\n",
       "      <td>17</td>\n",
       "      <td>2010-02-05</td>\n",
       "      <td>789036.02</td>\n",
       "      <td>0</td>\n",
       "      <td>23.11</td>\n",
       "      <td>2.666</td>\n",
       "      <td>126.442065</td>\n",
       "      <td>6.548</td>\n",
       "      <td>Regular Week</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4147</th>\n",
       "      <td>30</td>\n",
       "      <td>2010-02-05</td>\n",
       "      <td>465108.52</td>\n",
       "      <td>0</td>\n",
       "      <td>39.05</td>\n",
       "      <td>2.572</td>\n",
       "      <td>210.752605</td>\n",
       "      <td>8.324</td>\n",
       "      <td>Regular Week</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3574</th>\n",
       "      <td>25</td>\n",
       "      <td>2012-10-26</td>\n",
       "      <td>688940.94</td>\n",
       "      <td>0</td>\n",
       "      <td>56.69</td>\n",
       "      <td>3.882</td>\n",
       "      <td>216.151590</td>\n",
       "      <td>7.293</td>\n",
       "      <td>Regular Week</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>714</th>\n",
       "      <td>5</td>\n",
       "      <td>2012-10-26</td>\n",
       "      <td>319550.77</td>\n",
       "      <td>0</td>\n",
       "      <td>71.70</td>\n",
       "      <td>3.506</td>\n",
       "      <td>224.037814</td>\n",
       "      <td>5.422</td>\n",
       "      <td>Regular Week</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5719</th>\n",
       "      <td>40</td>\n",
       "      <td>2012-10-26</td>\n",
       "      <td>921264.52</td>\n",
       "      <td>0</td>\n",
       "      <td>49.65</td>\n",
       "      <td>3.917</td>\n",
       "      <td>138.728161</td>\n",
       "      <td>4.145</td>\n",
       "      <td>Regular Week</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2573</th>\n",
       "      <td>18</td>\n",
       "      <td>2012-10-26</td>\n",
       "      <td>1127516.25</td>\n",
       "      <td>0</td>\n",
       "      <td>56.09</td>\n",
       "      <td>3.917</td>\n",
       "      <td>138.728161</td>\n",
       "      <td>8.243</td>\n",
       "      <td>Regular Week</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6434</th>\n",
       "      <td>45</td>\n",
       "      <td>2012-10-26</td>\n",
       "      <td>760281.43</td>\n",
       "      <td>0</td>\n",
       "      <td>58.85</td>\n",
       "      <td>3.882</td>\n",
       "      <td>192.308899</td>\n",
       "      <td>8.667</td>\n",
       "      <td>Regular Week</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>6435 rows × 9 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "      Store       Date  Weekly_Sales  Holiday_Flag  Temperature  Fuel_Price  \\\n",
       "0         1 2010-02-05    1643690.90             0        42.31       2.572   \n",
       "1287     10 2010-02-05    2193048.75             0        54.34       2.962   \n",
       "5148     37 2010-02-05     536006.73             0        45.97       2.572   \n",
       "2288     17 2010-02-05     789036.02             0        23.11       2.666   \n",
       "4147     30 2010-02-05     465108.52             0        39.05       2.572   \n",
       "...     ...        ...           ...           ...          ...         ...   \n",
       "3574     25 2012-10-26     688940.94             0        56.69       3.882   \n",
       "714       5 2012-10-26     319550.77             0        71.70       3.506   \n",
       "5719     40 2012-10-26     921264.52             0        49.65       3.917   \n",
       "2573     18 2012-10-26    1127516.25             0        56.09       3.917   \n",
       "6434     45 2012-10-26     760281.43             0        58.85       3.882   \n",
       "\n",
       "             CPI  Unemployment Holiday_Status  \n",
       "0     211.096358         8.106   Regular Week  \n",
       "1287  126.442065         9.765   Regular Week  \n",
       "5148  209.852966         8.554   Regular Week  \n",
       "2288  126.442065         6.548   Regular Week  \n",
       "4147  210.752605         8.324   Regular Week  \n",
       "...          ...           ...            ...  \n",
       "3574  216.151590         7.293   Regular Week  \n",
       "714   224.037814         5.422   Regular Week  \n",
       "5719  138.728161         4.145   Regular Week  \n",
       "2573  138.728161         8.243   Regular Week  \n",
       "6434  192.308899         8.667   Regular Week  \n",
       "\n",
       "[6435 rows x 9 columns]"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "id": "vsgsbZcYKQPs",
    "outputId": "cda7b744-494d-4b23-8b25-1b95de2cf505"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Store             0\n",
      "Date              0\n",
      "Weekly_Sales      0\n",
      "Holiday_Flag      0\n",
      "Temperature       0\n",
      "Fuel_Price        0\n",
      "CPI               0\n",
      "Unemployment      0\n",
      "Holiday_Status    0\n",
      "dtype: int64\n"
     ]
    }
   ],
   "source": [
    "print(df.isnull().sum())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "id": "MGYIG5fPKscm",
    "outputId": "97b73d3f-3c23-443e-8691-839b0da38147"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Series([], dtype: int64)\n"
     ]
    }
   ],
   "source": [
    "missing = df.isnull().sum()\n",
    "print(missing[missing > 0])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 313
    },
    "id": "ac8a68a4",
    "outputId": "7b49f5cb-00e8-4ad5-bb72-752a0ed342ca"
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Store</th>\n",
       "      <th>Date</th>\n",
       "      <th>Weekly_Sales</th>\n",
       "      <th>Holiday_Flag</th>\n",
       "      <th>Temperature</th>\n",
       "      <th>Fuel_Price</th>\n",
       "      <th>CPI</th>\n",
       "      <th>Unemployment</th>\n",
       "      <th>Holiday_Status</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1</td>\n",
       "      <td>2010-02-05</td>\n",
       "      <td>1643690.90</td>\n",
       "      <td>0</td>\n",
       "      <td>42.31</td>\n",
       "      <td>2.572</td>\n",
       "      <td>211.096358</td>\n",
       "      <td>8.106</td>\n",
       "      <td>Regular Week</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1287</th>\n",
       "      <td>10</td>\n",
       "      <td>2010-02-05</td>\n",
       "      <td>2193048.75</td>\n",
       "      <td>0</td>\n",
       "      <td>54.34</td>\n",
       "      <td>2.962</td>\n",
       "      <td>126.442065</td>\n",
       "      <td>9.765</td>\n",
       "      <td>Regular Week</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5148</th>\n",
       "      <td>37</td>\n",
       "      <td>2010-02-05</td>\n",
       "      <td>536006.73</td>\n",
       "      <td>0</td>\n",
       "      <td>45.97</td>\n",
       "      <td>2.572</td>\n",
       "      <td>209.852966</td>\n",
       "      <td>8.554</td>\n",
       "      <td>Regular Week</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2288</th>\n",
       "      <td>17</td>\n",
       "      <td>2010-02-05</td>\n",
       "      <td>789036.02</td>\n",
       "      <td>0</td>\n",
       "      <td>23.11</td>\n",
       "      <td>2.666</td>\n",
       "      <td>126.442065</td>\n",
       "      <td>6.548</td>\n",
       "      <td>Regular Week</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4147</th>\n",
       "      <td>30</td>\n",
       "      <td>2010-02-05</td>\n",
       "      <td>465108.52</td>\n",
       "      <td>0</td>\n",
       "      <td>39.05</td>\n",
       "      <td>2.572</td>\n",
       "      <td>210.752605</td>\n",
       "      <td>8.324</td>\n",
       "      <td>Regular Week</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "      Store       Date  Weekly_Sales  Holiday_Flag  Temperature  Fuel_Price  \\\n",
       "0         1 2010-02-05    1643690.90             0        42.31       2.572   \n",
       "1287     10 2010-02-05    2193048.75             0        54.34       2.962   \n",
       "5148     37 2010-02-05     536006.73             0        45.97       2.572   \n",
       "2288     17 2010-02-05     789036.02             0        23.11       2.666   \n",
       "4147     30 2010-02-05     465108.52             0        39.05       2.572   \n",
       "\n",
       "             CPI  Unemployment Holiday_Status  \n",
       "0     211.096358         8.106   Regular Week  \n",
       "1287  126.442065         9.765   Regular Week  \n",
       "5148  209.852966         8.554   Regular Week  \n",
       "2288  126.442065         6.548   Regular Week  \n",
       "4147  210.752605         8.324   Regular Week  "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "display(df.head())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "xNn-hFmBLDBF"
   },
   "source": [
    "# Dashboard"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [],
   "source": [
    "W_BLUE = \"#0053E2\"    # PMS 2728 C\n",
    "W_YELLOW = \"#FFC220\"  # PMS 1235C\n",
    "W_WHITE = \"#FFFFFF\"   # PMS WHITE\n",
    "TEXT_MAIN = \"#001E60\" # PMS 2757C (Dark Blue)\n",
    "TEXT_LIGHT = \"#4DBDF5\" # PMS 297C (Medium Blue)\n",
    "TEXT_SOFT = \"#A9DDF7\" # PMS 9441C (Pale Blue)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Overwriting app.py\n"
     ]
    }
   ],
   "source": [
    "%%writefile app.py\n",
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import plotly.express as px\n",
    "\n",
    "# --- 1. BRAND IDENTITY & THEME ---\n",
    "W_BLUE = \"#0053E2\"    # Main Background Blue\n",
    "W_YELLOW = \"#FFC220\"  # Walmart Yellow\n",
    "W_WHITE = \"#FFFFFF\"   # Card Background\n",
    "TEXT_MAIN = \"#001E60\" # High-contrast Navy for inside cards\n",
    "TEXT_SOFT = \"#A9DDF7\" # Light blue for metric labels\n",
    "\n",
    "# --- 2. CONFIGURATION ---\n",
    "st.set_page_config(page_title=\"Walmart Retail Analytics Dashboard\", layout=\"wide\")\n",
    "\n",
    "st.markdown(f\"\"\"\n",
    "    <style>\n",
    "    @import url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700;800&display=swap');\n",
    "    \n",
    "    .stApp {{\n",
    "        background-color: {W_BLUE};\n",
    "        font-family: 'Open Sans', sans-serif;\n",
    "    }}\n",
    "\n",
    "    /* Title Styling */\n",
    "    .huge-title {{\n",
    "        font-size: 104px !important; \n",
    "        color: {W_WHITE}; \n",
    "        font-weight: 800;\n",
    "        text-align: center;\n",
    "        margin-bottom: 0px;\n",
    "        line-height: 0.8;\n",
    "        text-transform: uppercase;\n",
    "    }}\n",
    "\n",
    "    .sub-title {{\n",
    "        font-size: 30px !important;\n",
    "        color: {W_YELLOW};\n",
    "        font-weight: 700;\n",
    "        text-align: center;\n",
    "        margin-top: 10px;\n",
    "        letter-spacing: 5px;\n",
    "    }}\n",
    "\n",
    "    /* White Card Styling */\n",
    "    .content-card {{\n",
    "        background-color: {W_WHITE};\n",
    "        padding: 25px;\n",
    "        border-radius: 15px;\n",
    "        border: 2px solid {W_YELLOW};\n",
    "        box-shadow: 0px 4px 15px rgba(0,0,0,0.3);\n",
    "        margin-bottom: 20px;\n",
    "        color: #001E60 !important;\n",
    "    }}\n",
    "\n",
    "    .outside-text {{\n",
    "        color: {W_WHITE} !important;\n",
    "        font-weight: bold;\n",
    "        margin-bottom: 10px;\n",
    "    }}\n",
    "\n",
    "    .inside-text {{\n",
    "        color: {TEXT_MAIN} !important;\n",
    "        font-size: 22px !important;\n",
    "        font-weight: 500;\n",
    "        line-height: 1.6;\n",
    "    }}\n",
    "\n",
    "    [data-testid=\"stMetricValue\"] {{ font-size: 32px !important; color: {W_WHITE} !important; }}\n",
    "    [data-testid=\"stMetricLabel\"] {{ font-size: 16px !important; color: {TEXT_SOFT} !important; }}\n",
    "    [data-testid=\"stSidebar\"] {{ background-color: {W_WHITE}; }}\n",
    "\n",
    "    /* FIX: Yellow multiselect tags */\n",
    "    span[data-baseweb=\"tag\"] {{\n",
    "        background-color: #FFC220 !important;\n",
    "        color: #001E60 !important;\n",
    "        border-radius: 5px !important;\n",
    "    }}\n",
    "    \n",
    "    </style>\n",
    "    \"\"\", unsafe_allow_html=True)\n",
    "\n",
    "# --- 3. DATA LOADING ---\n",
    "@st.cache_data\n",
    "def load_data():\n",
    "    try:\n",
    "        df = pd.read_csv(\"Walmart_Sales.csv\")\n",
    "        df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)\n",
    "        return df\n",
    "    except:\n",
    "        return None\n",
    "\n",
    "df = load_data()\n",
    "\n",
    "if df is not None:\n",
    "    # --- 4. HEADER ---\n",
    "    st.markdown('<p class=\"huge-title\">WALMART</p>', unsafe_allow_html=True)\n",
    "    st.markdown('<p class=\"sub-title\">ANALYTICS</p>', unsafe_allow_html=True)\n",
    "\n",
    "    # --- 5. SIDEBAR ---\n",
    "    st.sidebar.image(\"walmart-logo-png-27971.png\", use_container_width=True)\n",
    "    st.sidebar.header(\"Filter Data\")\n",
    "    store_list = sorted(df['Store'].unique())\n",
    "    selected_stores = st.sidebar.multiselect(\"Select Store IDs\", store_list, default=store_list[:2])\n",
    "    \n",
    "    if not selected_stores:\n",
    "        st.warning(\"Please select a store to begin.\")\n",
    "    else:\n",
    "        filtered_df = df[df['Store'].isin(selected_stores)]\n",
    "\n",
    "        # --- 6. KPI SECTION ---\n",
    "        st.markdown('<p class=\"outside-text\" style=\"font-size:28px;\">Key Performance Indicators</p>', unsafe_allow_html=True)\n",
    "        k1, k2, k3, k4 = st.columns(4)\n",
    "        k1.metric(\"Avg Weekly Sales\", f\"${filtered_df['Weekly_Sales'].mean():,.2f}\")\n",
    "        k2.metric(\"Aggregate Revenue\", f\"${filtered_df['Weekly_Sales'].sum():,.0f}\")\n",
    "        k3.metric(\"Fuel Price Index\", f\"${filtered_df['Fuel_Price'].mean():.2f}\")\n",
    "        k4.metric(\"Unemployment Avg\", f\"{filtered_df['Unemployment'].mean():.2f}%\")\n",
    "\n",
    "       \n",
    "    # --- 7. VISUALIZATIONS (SLIM HEADERS & WHITE BACKGROUND) ---\n",
    "        col_a, col_b = st.columns(2)\n",
    "       \n",
    "        # Force white background for the charts and ensure grid lines are visible\n",
    "        chart_theme = dict(\n",
    "            paper_bgcolor='#FFFFFF', \n",
    "            plot_bgcolor='#FFFFFF',\n",
    "            font=dict(color=\"#001E60\", size=12), \n",
    "            margin=dict(l=50, r=30, t=20, b=50)\n",
    "        )\n",
    "\n",
    "        with col_a:\n",
    "            # Slim centered header\n",
    "            st.markdown(f'''\n",
    "                <div class=\"content-card\" style=\"padding: 10px; margin-bottom: 5px; text-align: center;\">\n",
    "                    <p style=\"color:#001E60; font-weight:bold; font-size:18px; margin:0;\">\n",
    "                        Sales Velocity Trend\n",
    "                    </p>\n",
    "                </div>\n",
    "            ''', unsafe_allow_html=True)\n",
    "            \n",
    "            trend_df = filtered_df.groupby(\"Date\")[\"Weekly_Sales\"].sum().reset_index()\n",
    "            fig_line = px.line(trend_df, x=\"Date\", y=\"Weekly_Sales\", color_discrete_sequence=[W_BLUE])\n",
    "            fig_line.update_layout(**chart_theme, height=350)\n",
    "            # Standardize axes for white background\n",
    "            fig_line.update_xaxes(showgrid=True, gridcolor='#EEEEEE', linecolor='#001E60')\n",
    "            fig_line.update_yaxes(showgrid=True, gridcolor='#EEEEEE', linecolor='#001E60')\n",
    "            \n",
    "            st.plotly_chart(fig_line, use_container_width=True)\n",
    "\n",
    "        with col_b:\n",
    "            # Slim centered header\n",
    "            st.markdown(f'''\n",
    "                <div class=\"content-card\" style=\"padding: 10px; margin-bottom: 5px; text-align: center;\">\n",
    "                    <p style=\"color:#001E60; font-weight:bold; font-size:18px; margin:0;\">\n",
    "                        Fuel Price vs. Sales\n",
    "                    </p>\n",
    "                </div>\n",
    "            ''', unsafe_allow_html=True)\n",
    "            \n",
    "            fig_scatter = px.scatter(filtered_df, x=\"Fuel_Price\", y=\"Weekly_Sales\", color_discrete_sequence=[\"#F47321\"])\n",
    "            fig_scatter.update_layout(**chart_theme, height=350)\n",
    "            # Standardize axes for white background\n",
    "            fig_scatter.update_xaxes(showgrid=True, gridcolor='#EEEEEE', linecolor='#001E60')\n",
    "            fig_scatter.update_yaxes(showgrid=True, gridcolor='#EEEEEE', linecolor='#001E60')\n",
    "            \n",
    "            st.plotly_chart(fig_scatter, use_container_width=True)\n",
    "            \n",
    "        # --- 8. DYNAMIC SUMMARY ---\n",
    "        st.markdown('<p class=\"outside-text\" style=\"font-size:40px; margin-top:30px;\">EXECUTIVE ANALYSIS SUMMARY</p>', unsafe_allow_html=True)\n",
    "        \n",
    "        top_store = filtered_df.groupby('Store')['Weekly_Sales'].sum().idxmax()\n",
    "        stores_str = \", \".join(map(str, selected_stores))\n",
    "\n",
    "        st.markdown(f\"\"\"\n",
    "            <div class=\"content-card\">\n",
    "                <div class=\"inside-text\">\n",
    "                    Currently evaluating retail data for <strong>Store(s): {stores_str}</strong>.<br><br>\n",
    "                    Data insights suggest that <strong>Store {top_store}</strong> leads in revenue generation within this cluster. \n",
    "                    Performance remains consistent despite economic shifts in fuel pricing and unemployment rates.\n",
    "                </div>\n",
    "            </div>\n",
    "        \"\"\", unsafe_allow_html=True)\n",
    "\n",
    "    # --- 9. FOOTER ---\n",
    "    st.markdown(f\"\"\"\n",
    "        <div style=\"text-align:center; padding: 40px; color:white; border-top: 1px solid {TEXT_SOFT}; margin-top:50px;\">\n",
    "            <p style=\"font-size:18px;\"><strong>Business Analysts:</strong> Sheikha Maris Nicolas, Duane Ryann Montes, Mikaela Angela Patopaten</p>\n",
    "            <p>© 2026 Business Analytics Project</p>\n",
    "        </div>\n",
    "    \"\"\", unsafe_allow_html=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "!streamlit run app.py"
   ]
  }
 ],
 "metadata": {
  "colab": {
   "provenance": []
  },
  "kernelspec": {
   "display_name": "Python [conda env:aanconda new] *",
   "language": "python",
   "name": "conda-env-aanconda_new-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
